config/routes.rb
Backlog::Application.routes.draw do
  get "dashboard/index"

  resources :schemas do
    resources :issuetypes
  end

  resources :projects do
    resources :backlogentries
  end

  root :to => 'dashboard#index'

end

app/models/backlogentry.rb
class Backlogentry < ActiveRecord::Base
  belongs_to :project
  belongs_to :issuetype
end

app/controllers/backlogentries_controller.rb
class BacklogentriesController < ApplicationController
  # GET /backlogentries
  # GET /backlogentries.json
  def index
    @backlogentries = Backlogentry.find_all_by_project_id(params[:project_id])
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @backlogentries }
    end
  end

  # GET /backlogentries/1
  # GET /backlogentries/1.json
  def show
    @backlogentry = Backlogentry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @backlogentry }
    end
  end

  # GET /backlogentries/new
  # GET /backlogentries/new.json
  def new
    @backlogentry = Backlogentry.new
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: [@project,@backlogentry] }
    end
  end

  # GET /backlogentries/1/edit
  def edit
    @backlogentry = Backlogentry.find(params[:id])
    @project = Project.find(@backlogentry.project_id)
  end

  # POST /backlogentries
  # POST /backlogentries.json
  def create
    @backlogentry = Backlogentry.new(params[:backlogentry])

    respond_to do |format|
      if @backlogentry.save
        format.html { redirect_to project_backlogentries_path(@backlogentry.project), notice: 'Backlogentry was successfully created.' }
        #format.json { render json: @backlogentry, status: :created, location: @backlogentry }
      else
        format.html { render action: "new" }
        format.json { render json: @backlogentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /backlogentries/1
  # PUT /backlogentries/1.json
  def update
    @backlogentry = Backlogentry.find(params[:id])

    respond_to do |format|
      if @backlogentry.update_attributes(params[:backlogentry])
        format.html { redirect_to project_backlogentries_path(@backlogentry.project), notice: 'Backlogentry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @backlogentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backlogentries/1
  # DELETE /backlogentries/1.json
  def destroy
    @backlogentry = Backlogentry.find(params[:id])
    @project = @backlogentry.project
    @backlogentry.destroy

    respond_to do |format|
      format.html { redirect_to project_backlogentries_url @project}
      format.json { head :ok }
    end
  end
end

app/helpers/backlogentries_helper.rb
module BacklogentriesHelper
end

app/views/backlogentries/_form.html.erb
<%= form_for([@project,@backlogentry]) do |f| %>
  <% if @backlogentry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@backlogentry.errors.count, "error") %> prohibited this backlogentry from being saved:</h2>

      <ul>
      <% @backlogentry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :resolution %><br />
    <%= f.number_field :resolution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backlogentries/edit.html.erb
<h1>Editing backlogentry</h1>

<%= render 'form' %>

<%= link_to 'Show', project_backlogentry_path(@project,@backlogentry) %> |
<%= link_to 'Back', project_backlogentries_path(@project) %>

app/views/backlogentries/index.html.erb
<h1>Listing backlogentries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Resolution</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @backlogentries.each do |backlogentry| %>
  <tr>
    <td><%= backlogentry.title %></td>
    <td><%= backlogentry.description %></td>
    <td><%= backlogentry.status %></td>
    <td><%= backlogentry.priority %></td>
    <td><%= backlogentry.resolution %></td>
    <td><%= link_to 'Show', project_backlogentry_path(@project,backlogentry) %></td>
    <td><%= link_to 'Edit', edit_project_backlogentry_path(@project,backlogentry) %></td>
    <td><%= link_to 'Destroy', [@project,backlogentry], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Backlogentry', new_project_backlogentry_path(@project) %>
<%= link_to 'Back to Projects', projects_path%>

app/views/backlogentries/new.html.erb
<h1>New backlogentry</h1>

<%= render 'form' %>

<%= link_to 'Back', project_backlogentries_path(@project) %>

app/views/backlogentries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @backlogentry.title %>
</p>

<p>
  <b>Description:</b>
  <%= @backlogentry.description %>
</p>

<p>
  <b>Status:</b>
  <%= @backlogentry.status %>
</p>

<p>
  <b>Priority:</b>
  <%= @backlogentry.priority %>
</p>

<p>
  <b>Resolution:</b>
  <%= @backlogentry.resolution %>
</p>


<%= link_to 'Edit', edit_project_backlogentry_path(@backlogentry.project,@backlogentry) %> |
<%= link_to 'Back', project_backlogentries_path(@project) %>