config/routes.rb
Backlog::Application.routes.draw do
  get "dashboard/index"

  resources :schemas do
    resources :issuetypes
  end

  resources :projects do
    resources :backlogentries
  end

  root :to => 'dashboard#index'

end

app/controllers/issuetypes_controller.rb
class IssuetypesController < ApplicationController
  # GET /issuetypes
  # GET /issuetypes.json
  def index
    @issuetypes = Issuetype.find_all_by_schema_id(params[:schema_id])
    @schema = Schema.find(params[:schema_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issuetypes }
    end
  end

  # GET /issuetypes/1
  # GET /issuetypes/1.json
  def show
    @issuetype = Issuetype.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issuetype }
    end
  end

  # GET /issuetypes/new
  # GET /issuetypes/new.json
  def new
    @issuetype = Issuetype.new
    @schema = Schema.find(params[:schema_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issuetype }
    end
  end

  # GET /issuetypes/1/edit
  def edit
    @issuetype = Issuetype.find(params[:id])
    @schema = @issuetype.schema
  end

  # POST /issuetypes
  # POST /issuetypes.json
  def create
    @issuetype = Issuetype.new(params[:issuetype])
    @issuetype.schema = Schema.find(@issuetype.schema_id)
    respond_to do |format|
      if @issuetype.save
        format.html { redirect_to schema_issuetypes_path(@issuetype.schema), notice: 'Issuetype was successfully created.' }
        #format.json { render json: @issuetype, status: :created, location: @issuetype }
      else
        format.html { render action: "new" }
        format.json { render json: @issuetype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issuetypes/1
  # PUT /issuetypes/1.json
  def update
    @issuetype = Issuetype.find(params[:id])

    respond_to do |format|
      if @issuetype.update_attributes(params[:issuetype])
        format.html { redirect_to schema_issuetypes_url(@issuetype.schema), notice: 'Issuetype was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @issuetype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issuetypes/1
  # DELETE /issuetypes/1.json
  def destroy
    @issuetype = Issuetype.find(params[:id])
    #@schema = Schema.find(@issuetype.schema_id)
    @issuetype.destroy

    respond_to do |format|
      format.html { redirect_to schema_issuetypes_path(@issuetype.schema), notice: 'Issuetype was successfully destroied.' }
      format.json { head :ok }
    end
  end
end

app/helpers/issuetypes_helper.rb
module IssuetypesHelper
end

app/views/issuetypes/_form.html.erb
<%= form_for([@schema,@issuetype]) do |f| %>
  <% if @issuetype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issuetype.errors.count, "error") %> prohibited this issuetype from being saved:</h2>

      <ul>
      <% @issuetype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :schema_id %><br />
    <%= f.text_field :schema_id %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issuetypes/edit.html.erb
<h1>Editing issuetype</h1>

<%= render 'form' %>

<%= link_to 'Show', schema_issuetype_path(@schema,@issuetype) %> |
<%= link_to 'Back', schema_issuetypes_path(@schema) %>

app/views/issuetypes/index.html.erb
<h1>Listing issuetypes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issuetypes.each do |issuetype| %>
  <tr>
    <td><%= issuetype.name %></td>
    <td><%= issuetype.active %></td>
    <td><%= link_to 'Show',schema_issuetype_path(@schema,issuetype)%></td>
    <td><%= link_to 'Edit',edit_schema_issuetype_path(@schema,issuetype)%></td>
    <td><%= link_to 'Destroy', [@schema,issuetype] ,confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
                                                                                  
<br />

<%= link_to 'New Issuetype', new_schema_issuetype_path(@schema) %>
<%= link_to 'Back to Schema',schemas_path %>

app/views/issuetypes/new.html.erb
<h1>New issuetype</h1>

<%= render 'form' %>

<%= link_to 'Back', schema_issuetypes_path(@schema) %>

app/views/issuetypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @issuetype.name %>
</p>

<p>
  <b>Active:</b>
  <%= @issuetype.active %>
</p>


<%= link_to 'Edit', edit_schema_issuetype_path(@issuetype) %> |
<%= link_to 'Back', schema_issuetypes_path %>