config/routes.rb
Backlog::Application.routes.draw do
  get "dashboard/index"

  resources :schemas do
    resources :issuetypes
  end

  resources :projects do
    resources :backlogentries
  end

  root :to => 'dashboard#index'

end

app/models/schema.rb
class Schema < ActiveRecord::Base
  has_many :issuetypes
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController
  # GET /schemas
  # GET /schemas.json
  def index
    @schemas = Schema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schemas }
    end
  end

  # GET /schemas/1
  # GET /schemas/1.json
  def show
    @schema = Schema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schema }
    end
  end

  # GET /schemas/new
  # GET /schemas/new.json
  def new
    @schema = Schema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schema }
    end
  end

  # GET /schemas/1/edit
  def edit
    @schema = Schema.find(params[:id])
  end

  # POST /schemas
  # POST /schemas.json
  def create
    @schema = Schema.new(params[:schema])

    respond_to do |format|
      if @schema.save
        format.html { redirect_to @schema, notice: 'Schema was successfully created.' }
        format.json { render json: @schema, status: :created, location: @schema }
      else
        format.html { render action: "new" }
        format.json { render json: @schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schemas/1
  # PUT /schemas/1.json
  def update
    @schema = Schema.find(params[:id])

    respond_to do |format|
      if @schema.update_attributes(params[:schema])
        format.html { redirect_to @schema, notice: 'Schema was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schemas/1
  # DELETE /schemas/1.json
  def destroy
    @schema = Schema.find(params[:id])
    @schema.destroy

    respond_to do |format|
      format.html { redirect_to schemas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/schemas_helper.rb
module SchemasHelper
end

app/views/schemas/_form.html.erb
<%= form_for(@schema) do |f| %>
  <% if @schema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schema.errors.count, "error") %> prohibited this schema from being saved:</h2>

      <ul>
      <% @schema.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schemas/edit.html.erb
<h1>Editing schema</h1>

<%= render 'form' %>

<%= link_to 'Show', @schema %> |
<%= link_to 'Add IssueType', new_schema_issuetype_path(@schema) %> |
<%= link_to 'Back', schemas_path %>

app/views/schemas/index.html.erb
<h1>Listing schemas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schemas.each do |schema| %>
  <tr>
    <td><%= schema.title %></td>
    <td><%= schema.description %></td>
    <td><%= schema.active %></td>
    <td><%= link_to 'Show', schema %></td>
    <td><%= link_to 'Edit', edit_schema_path(schema) %></td>
    <td><%= link_to 'Issue Types', schema_issuetypes_path(schema) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schema', new_schema_path %>

app/views/schemas/new.html.erb
<h1>New schema</h1>

<%= render 'form' %>

<%= link_to 'Back', schemas_path %>

app/views/schemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @schema.title %>
</p>

<p>
  <b>Description:</b>
  <%= @schema.description %>
</p>

<p>
  <b>Active:</b>
  <%= @schema.active %>
</p>


<%= link_to 'Edit', edit_schema_path(@schema) %> |
<%= link_to 'Back', schemas_path %>